
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_HOST: "postgres"
    volumes:
      - database:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack

  api:
    container_name: proximityservice
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_HOST: "postgres"
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  database: 
  api_volume:

networks:
  fullstack:
    driver: bridge
